# Generated by Django 3.2.6 on 2021-08-24 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Genure', models.CharField(max_length=20)),
                ('Release_Date', models.DateTimeField()),
                ('avg_rating', models.IntegerField()),
                ('Language', models.CharField(max_length=20)),
                ('Artist', models.CharField(max_length=20)),
                ('Length', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Awards', models.ManyToManyField(to='home.Awards')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=20)),
                ('Votes', models.IntegerField()),
                ('Movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Date_of_Birth', models.DateTimeField()),
                ('Gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='male', max_length=10)),
                ('Awards', models.ManyToManyField(to='home.Awards')),
                ('movie', models.ManyToManyField(to='home.Movie')),
            ],
        ),
    ]
