# Generated by Django 3.2.6 on 2021-08-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210825_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='award',
            field=models.ManyToManyField(blank=True, null=True, to='home.Award'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='awards',
            field=models.ManyToManyField(blank=True, null=True, to='home.Award'),
        ),
    ]
