# Generated by Django 3.2.6 on 2021-09-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manage', '0002_alter_document_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
