# Generated by Django 3.2.6 on 2021-09-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manage', '0003_alter_document_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
