# Generated by Django 3.2.6 on 2021-08-23 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Travel', 'Travel'), ('Education', 'Education'), ('Gifts_and_Donations', 'Gifts_and_Donations'), ('Investments', 'Investments'), ('Bills_and_Utilities', 'Bills_and_Utilities'), ('Food_and_Dining', 'Food_and_Dining'), ('Health_and_Fitness', 'Health_and_Fitness'), ('Personal_Care', 'Personal_Care'), ('Fees_and_Charges', 'Fees_and_Charges')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('add_money', models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('Date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
