# Generated by Django 3.2.6 on 2021-08-12 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serves_burger', models.BooleanField(default=False)),
                ('serves_pizz', models.BooleanField(default=False)),
                ('places', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.place')),
            ],
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('resturant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.restaurant')),
            ],
        ),
    ]
